language: python
notifications:
  email: false
  slack:
    secure: lIwXc6cx3Dzwd+ryzvxCYT/Ckl5c0kXTgSPMQExF9r8zZaQ8APBq7W/dH+YVqpMhvCK65DxTf5+yxTpj8o3PrvfBOOMvDmRqyM1+pcCrumS1TvG3hd7OQ9ikC3K1JPEjejVHjVaGb6wZkTUQmSYxNXXYkAbP6IkG3iV5D/3fB/O/MFE5aaAnWXkUYbQexJAfQbzJc0HZrUWv8owuVG97EZSDgA2/nblhYOFKmt3tmzSRUs8pjuYO7KW0OeTClcqowqxjZ/Spt8QdkuEs2EIYaI8illhKtJPE7w6YbC+7cYh6gGXuDpnh5J4ur2AqbafcpHmZ71blHgRehMeJTH3f0Wn+TKly9hqw+YIrqp7DoaSX4u/GskeTLJ7ijJXwUU3zeKlLu11sFcnmv/ciVS+naT4aznmqKpmE/x3eeSUfm/Rk42uzGVUjYAIMFf31+KbdbeusLkFpzeoA3TGijalqW3rD0xc4V/+W2bHgTdp8u5xE5F/iJ+DrPyxEax0wsxJrtmBZU1Khobulsq1+kxy4TfFYV2Njbp6YQQ3Un3vmn+2ZVUV6s4/MaWwdCiylVK2fGezyRobrmA7Qou80+aA5oR6jpra+A+zf04W0jDQrBV2c1ovuX+nq53QXn4OqZIRfcvNjnHk94I4YCM9KsXr4cvuC6cdIOyRB6KMtBudvKow=
branches:
  only:
  - gtharris-dev
deploy:
  provider: heroku
  app: boxd
  api_key:
    secure: R4WG0YWGqv+3Hff6S/ljGFO5hsrOrBIluS/5rMKCqfpfxfF5LwW+pY3TLwKkYJ8f+U/WeU4cKqUsccKIvuuslVc17xp8lNlAuznajHl6T/AS802KCm5X7lLzsLoKsUtnXR2a/kmjiulg2De2VCT1noeJdzU2uSOAaw+Hj5YsQJrnbCjCFuDVQaRlXemS2gjJMxqxdqafFKEroyXNd+7X3/n67r/Q6UqqOxdWHX3PMGFawEXOB6+rh3Vwu34j/QvzXqDMa4JQgX91jDCQ8h+OO2W3hwyce7NvkQK4F7CMQ9Sn+yUBjqjI4PUEhHB8NVPEyrk6HhYPzEsY419Ynl73rZRv5xg6wLpz0fChpQZqFGlgtLebY1XatriXnO+2JSBV/esKxI27WM8QGInmXT1MF0i6+yAPBUsmr6PIcjOdFkz4JnOp3PFINKPp2fLTAKk2HQ/tMgnNc4ng3PbZa29GQjXgVGnuoDf/L/harFvbz93lSBUCBtuglpPHaDSlRDrU0MikSblKOZ1g7R+b12s0j5koNUg4mwdODtVkPGdrPMzKEVpAJoSZ6/yAeTtMYQ3rGl2Dyn+dsd8lFSbk0BTF5f8vqmApBwlYFgeFQtyXoCZNywwn0CK/zz1TCTfxLaSCxVurPfDH5mf6TTPOQU2PsbyYTazgCh8ZIHc9heoZ9KE=
